package com.gymprofit.api.enums;

public enum TipoObjetivo {
    PERDER_PESO,
    GANAR_MASA_MUSCULAR,
    MEJORAR_RESISTENCIA,
    MEJORAR_FLEXIBILIDAD,
    MEJORAR_FUERZA,
    MANTENER_PESO,
    REDUCIR_GRASA_CORPORAL,
    MEJORAR_VELOCIDAD,
    AUMENTAR_CALORIAS,
    MEJORAR_MOVILIDAD,
    COMPLETAR_RETO,
    OTRO
}