UPDATE usuarios
SET objetivo = 'OTRO'
WHERE objetivo IS NOT NULL
  AND objetivo NOT IN (
    'PERDER_PESO', 'GANAR_MASA_MUSCULAR', 'MEJORAR_RESISTENCIA',
    'MEJORAR_FLEXIBILIDAD', 'MEJORAR_FUERZA', 'MANTENER_PESO',
    'REDUCIR_GRASA_CORPORAL', 'MEJORAR_VELOCIDAD', 'AUMENTAR_CALORIAS',
    'MEJORAR_MOVILIDAD', 'COMPLETAR_RETO', 'OTRO'
  );

ALTER TABLE usuarios MODIFY COLUMN objetivo VARCHAR(50);
